export { default as Root } from "./Root"
export { default as NotFound } from "./Error"
export { default as Login } from "./Login"
export { default as Profile } from "./Profile"
export { default as Register } from "./Register"
export { default as Home } from "./Home"
export { default as Routine } from "./Routine"
export { default as Activity } from "./Activity"